# An example configuration:
#TechDivision:
#  CkStyles:
#    InlineStyles:
#      presets:
#        'fontColor':
#          label: 'Font color'
#          options:
#            'primary':
#              label: 'Red'
#              cssClass: 'my-class-red'
#            'secondary':
#              label: 'Green'
#              cssClass: 'my-class-green'
#            '':
#              label: 'unset color'
#              cssClass: null
#    BlockStyles:
#      presets:
#        'indent':
#          label: 'Indentation'
#          options:
#            'primary':
#              label: '2 rem'
#              cssClass: 'indent-2'
#            'secondary':
#              label: '4 rem'
#              cssClass: 'indent-4'
#            '':
#              label: 'remove indent'
#              cssClass: null


# DO NOT REMOVE BELOW
# apply javascript and configuration paths
Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'TechDivision.CkStyles:Styles':
            resource: resource://TechDivision.CkStyles/Public/JavaScript/CkStyles/Plugin.js
      frontendConfiguration:
        'TechDivision.CkStyles:InlineStyles': '${Configuration.setting(''TechDivision.CkStyles.InlineStyles'')}'
        'TechDivision.CkStyles:BlockStyles': '${Configuration.setting(''TechDivision.CkStyles.BlockStyles'')}'
